### ISSUE TITLE
`doctrine/cache` is sunset

### ISSUE THREAD

**Issue by greg0ire** [doctrine/persistence#184]
Since `doctrine/cache` is being sunset, we should stop relying on it.

**Comment by stof** [comment]
This has been implemented. PSR-6 is now supported natively in the AbstractClassMetadataFactory, and doctrine/cache is used only in the deprecated methods of the BC layer.

**Comment by derrabus** [comment]
So let's get rid of that BC layer as well. 🙂 

#220
