### ISSUE TITLE
ObjectManager::merge and detach deprecation messages

### ISSUE THREAD

**Issue by AntoineRoue** [doctrine/persistence#207]
Hello,

Since version 1.2 of this bundle, the methods ObjectManager::merge and ObjectManager::detach are commented as deprecated and to be removed in Persistence 2.0. However, these methods are still declared in ObjectManager of version 2.x and 3.0.x. So are merge and detach still deprecated methods ? And if so, when will it be removed ?

**Comment by malarzm** [comment]
To be honest we're still struggling with those deprecations. Personally I think the `merge` should be gone as mostly it brings nothing but troubles, but `detach` is still valueable especially for batch processing one and should stay

**Comment by AntoineRoue** [comment]
Ok. I don't think it's worth it to change the deprecated comment of these methods then. I close the issue.
