### ISSUE TITLE
Bump doctrine/cache to 2.1?

### ISSUE THREAD

**Issue by utkarsh2102** [doctrine/persistence#228]
Hello,

https://github.com/doctrine/persistence/blob/f8af155c1e7963f3d2b4415097d55757bbaa53d8/composer.json#L24

Could this be bumped to 2.1, please? This is making a lot of things fail, unfortunately, on the Debian and Ubuntu side. :/

**Comment by stof** [comment]
This constraint definitely *allows* installing 2.1. But it does not forbid using older versions, because there is nothing in doctrine/persistence being incompatible with them. So I don't see any reason to do it.

> This is making a lot of things fail, unfortunately, on the Debian and Ubuntu side.

what do you mean here ?

**Comment by greg0ire** [comment]
No answer… I'm closing this.
