### ISSUE TITLE
Unexpected response returned from `AbstractManagerRegistry::getManagerNames()`

### ISSUE THREAD

**Issue by jderusse** [doctrine/persistence#233]
The `ManagerRegistry::getManagerNames()` should return `An array of object manager names. string[]`

https://github.com/doctrine/persistence/blob/0130920efd696cf5480744f499672b2d4ca47c85/lib/Doctrine/Persistence/ManagerRegistry.php#L65-L70

But the implementation in `AbstractManagerRegistry` returns an array of serviceId indexed by name.

https://github.com/doctrine/persistence/blob/0130920efd696cf5480744f499672b2d4ca47c85/lib/Doctrine/Persistence/AbstractManagerRegistry.php#L194-L197

I'm not sure what is the expected response. I would expect that `getManagerNames` returned `['foo', 'bar']`. I would expect such code worked: But this is not the case.

```php
foreach ($this->registry->getManagerNames() as $name) {
  dump($this->registry->getManager($name));
}
```

But fixing it in the `AbstractManagerRegistry` class could be a BC break.
Otherwise, we should improve the documentation of the interface.

**Comment by greg0ire** [comment]
Note that the interface has been changed in 3.0: https://github.com/doctrine/persistence/pull/50
That method does not seem to be covered by any tests though :(

[An org-wide search](https://github.com/search?q=org%3Adoctrine+getManagerNames&type=code) shows that it is supposed to return `array<string, string>`. I think it's fine to improve the documentation in the interface. I'm on it.

**Comment by jderusse** [comment]
thank you for taking care of it.

For the record, the [laravel-doctrine/orm](https://github.com/laravel-doctrine/orm/blob/665e89bc8356be03ea44d7f52fcd795abedbd04a/src/IlluminateRegistry.php#L241-L243) project and many [snippet of codes](https://hotexamples.com/fr/examples/doctrine.common.persistence/ManagerRegistry/getManagerNames/php-managerregistry-getmanagernames-method-examples.html) expect the name to be the value (and not the index).

But your proposal is consistent with changes made in #50

**Comment by greg0ire** [comment]
TIL about this project. @eigan,hi :wave:  I think you will be interested in this.

**Comment by eigan** [comment]
Just to clarify. There is no implementation change in doctrine/persistence, just an update to the doc to clarify that it does not return names, but service-id? Is `getDefaultManagerName()` also a service-id?

This method `ManagerRegistry::getManager(?string $name = null)`. `$name` is the actual name, and not service-id. So there seems to be some mix of interpretation of what a "name" is(?)

Looking at the code in laravel-doctrine, it seems like it returns the name, and never exposes the service-ids.



Thanks to letting me know 🙂

**Comment by jderusse** [comment]
> to clarify that it does not return names, but service-id

It returns the `name` in the array's key (and not the array's value).

To be clear, it returns `['name 1' => 'id 1', 'name 2' => 'id 2']` where `id 1` and `id 2` are not relevant.
While people might expect `[0 => 'name 1', 1 => 'name 2']` where `0` and `1` are not relevant.

Iterating over the `getDefaultManagerName` should takes the key into account

```diff
-foreach ($registry->getDefaultManagerName() as $name) {
+foreach ($registry->getDefaultManagerName() as $name => $ignoreMe) {
   $registry->getManager($name);
 }
```

Looking at `laravel-doctrine` it [does the same thing](https://github.com/laravel-doctrine/orm/blob/665e89bc8356be03ea44d7f52fcd795abedbd04a/src/IlluminateRegistry.php#L230), BUT `laravel-doctrine` use [the same data](https://github.com/laravel-doctrine/orm/blob/665e89bc8356be03ea44d7f52fcd795abedbd04a/src/IlluminateRegistry.php#L84) for the both the `key` and the `value` => so this is less problematic.
