### ISSUE TITLE
Cache key contains reserved characters

### ISSUE THREAD

**Issue by lugosium** [doctrine/persistence#288]
Hello,

After upgrading to doctrine persistence 3, i have this error on cache clear:

```
In CacheItem.php line 159:
!!
!!    Cache key "AppBundle:EntityName__CLASSMETADATA__" contains reserved
!!    characters "{}()/\@:".
```

I looked at https://github.com/doctrine/persistence/blob/3.0.x/UPGRADE.md#upgrade-to-30 to upgrade correctly.

I thought it was my configuration:

```
naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
```

But it's not that.

EDIT: I am not sure issue should be here 🤔 

Thank you.

**Comment by malarzm** [comment]
Looking at `AppBundle:EntityName` it seems like you're still using short name aliases which were removed in 3.0 (BC Break: removed support for short namespace aliases). Please use FQCNs instead.

**Comment by lugosium** [comment]
Ah! I forgot to replace these in my configuration for my services.

In case it helps Symfony users, you need to replace:

```
- "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:EntityName')"
```

By

```
- "@=service('doctrine.orm.entity_manager').getRepository('AppBundle\\\\Entity\\\\EntityName')"
```

Thank you very much @malarzm
