### ISSUE TITLE
Issues with the compatibility of getRepository() function in MongoDB DocumentManager and Persistence ManagerRegistry

### ISSUE THREAD

**Issue by ThePaglia** [doctrine/persistence#353]
I am getting this error:
Compile Error: Declaration of Doctrine\ODM\MongoDB\DocumentManager::getRepository($className) must be compatible with Doctrine\Persistence\ManagerRegistry::getRepository(string $persistentObject, ?string $persistentManagerName = null)
Has anyone ever seen this error?
![image](https://github.com/doctrine/persistence/assets/116651982/3e467da9-4a04-417a-bb0d-8ccb2352639c)

**Comment by stof** [comment]
this error does not make any sense. DocumentManager is meant to implement the ObjectManager interface, not the ManagerRegistry interface.
And this is what it does in https://github.com/doctrine/mongodb-odm/blob/2a9429659f6dd2dead2c0fcb2406f9d14d31d55e/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L55

To me, it looks like your vendor folder is messed up.

**Comment by ThePaglia** [comment]
I tried removing the wrong implementation from the documentManager and now it works.
Somehow it got added automatically.
Here's how it looked: 
![image](https://github.com/doctrine/persistence/assets/116651982/919dda68-420a-4bba-859d-527fbbe3c92b)
