### ISSUE TITLE
Should there be an AbstractConnectionRegistry?

### ISSUE THREAD

**Issue by mattsah** [doctrine/persistence#64]
It appears that the ManagerRegistry interface extends the ConnectionRegistry.  It feels a bit like the AbstractManagerRegistry should extend an AbstractConnectionRegistry so they could be overloaded at either point.  If someone wanted just a ConnectionRegistry it would be easier to work with.

**Comment by stof** [comment]
ConnectionRegistry should be dropped in v2, as its types are `mixed` anyway, given there is no shared connection interface between the various Doctrine projects. We should rather have a dedicated ConnectionRegistry interface in DBAL to have proper types on it.

**Comment by alcaeus** [comment]
As @stof mentioned, we will be phasing out the connection registry interfaces. These have nothing to do with persistence, but rather are an implementation detail.
