### ISSUE TITLE
StaticPHP driver quoting reserved SQL keyword problem

### ISSUE THREAD

**Issue by knnnrd** [doctrine/persistence#66]
Hi,

We are having a problem with a database column name. The column's name is `default` which is an SQL reserved keyword. We are using the StaticPHP metadata driver.

According to the docs this should be fixable by manually quoting the column name with backticks. The official docs provide an annotation example, but this is not useful to us.

We are getting the follow exception:
```
ReflectionException
Property App\Printer\Entities\Printer::$`default` does not exist
```

Thanks in advance,

**Comment by malarzm** [comment]
@knnnrd please paste your mapping

**Comment by knnnrd** [comment]
```
$builder->createField("`default`", Type::STRING)
           ->length(1)
           ->option('fixed', true)
           ->option('default', '')
           ->option('comment', 'y,n')
           ->columnName('default')
           ->build();
```
