### ISSUE TITLE
Compile Error: Declaration of Doctrine XmlDriver

### ISSUE THREAD

**Issue by wkwkgit** [doctrine/persistence#78]
Symfony 4.4, on composer u i got this:

  - Updating doctrine/persistence (1.2.0 => 1.3.0): Loading from cache
!!  In XmlDriver.php line 881:
!!                                                                                 
!!    Compile Error: Declaration of Doctrine\ORM\Mapping\Driver\XmlDriver::loadMe  
!!    tadataForClass($className, Doctrine\Common\Persistence\Mapping\ClassMetadat  
!!    a $metadata) must be compatible with Doctrine\Persistence\Mapping\Driver\Ma  
!!    ppingDriver::loadMetadataForClass($className, Doctrine\Persistence\Mapping\  
!!    ClassMetadata $metadata)

**Comment by greg0ire** [comment]
Can you manually add `class_exists(\Doctrine\Common\Persistence\Mapping\ClassMetadata::class);` at the end of `Doctrine\Persistence\Mapping\Driver\MappingDriver` and report back?

**Comment by scuben** [comment]
I just ran into the same issue.

**Comment by greg0ire** [comment]
Can any of you try #79 ? I added some instructions. Also, please give your version of php, for science.

**Comment by greg0ire** [comment]
>  I do not have the issue on latest PHP 7.2.25 but do have the issue on 7.2.19.

Ah great, thanks for reporting this!

**Comment by scuben** [comment]
> Can any of you try #79 ? I added some instructions for you in the top message. Also, please give your version of php, for science.

Your PR works on 7.2.19 too. Thank you!

**Comment by greg0ire** [comment]
Thank you for reporting and testing!

**Comment by greg0ire** [comment]
Anyone experiencing this, please report what php version you use if it's a 7.2 one and higher than 7.2.19, or if it's not a 7.2 one.

**Comment by wkwkgit** [comment]
> Anyone experiencing this, please report what php version you use if it's a 7.2 one and higher than 7.2.19, or if it's not a 7.2 one.

OSX:
$ php -v
PHP 7.2.25

**Comment by greg0ire** [comment]
Oh wow that's weird, @scuben said it worked on his machine with that version. Are you sure you are not using another version (with virtualization, maybe)

**Comment by alcaeus** [comment]
1.3.1 has been released. Please open a new issue if you encounter problems.

**Comment by scuben** [comment]
For me it works now on both PHP versions.

**Comment by greg0ire** [comment]
I can't reproduce this on the official `7.2.19-cli` Docker image. I'd love to get more details, I've tried the following minimal script:

```php
<?php

require 'vendor/autoload.php';

use Doctrine\ORM\Mapping\Driver\XmlDriver;

new XmlDriver;
```

@scuben can you try the script above on your machine with 7.2.19 and tell us if it crashes with the error above or not? And if not, can you please try giving a minimal reproducer that does not involve `composer`, but just a simple php script like above?

**Comment by scuben** [comment]
@greg0ire Any chance you did misread my comment and switched "now" to "not"? :)

**Comment by greg0ire** [comment]
No, I fully understand, the thing is, I'd like to revert my fix and replace it with some Composer constraints like `php: ^7.2.21`. The things is, I don't don't know which versions of php have the issue, so I tried reproducing the bug on `7.2.19` by using Docker, but couldn't.

**Comment by scuben** [comment]
You might try it with symfony/composer as it happened on cache:clear after composer install for me. I can't create a script to reproduce the bug too because I just have limited time these days and not much knowledge to use orm or persitence separately and not within a symfony context.

**Comment by greg0ire** [comment]
The script I wrote above can be tried within a symfony context. You can name it crash.php, put it at the root of your project and run it with `php crash.php`. Can you please try that? :pray:

**Comment by greg0ire** [comment]
Good news I reproduced the bug thanks to [this comment](https://github.com/twigphp/Twig/pull/2887#issuecomment-472023116) (I would thank stof but I think he has enough notifications as is, so if you come across this issue, stof, thanks again <3)

Here is the code:

```
<?php

require 'vendor/autoload.php';

use Doctrine\ORM\Mapping\Driver\XmlDriver;
use Doctrine\Persistence\Mapping\Driver\FileDriver;

class_exists(FileDriver::class);
class_exists(XmlDriver::class);
```

I just have to do a bisection now :)

**Comment by greg0ire** [comment]
Well, I do have the bug for 7.2.25 too… I guess when you upgraded, it changed the order in which the classes were loaded for some obscure reason @scuben

**Comment by greg0ire** [comment]
7.3.12 has the crash too, but 7.4.0 does not.

**Comment by scuben** [comment]
Glad you could reproduce. It must somehow be connected with a composer install on my side.
