### ISSUE TITLE
doctrine/persistence 1.3.2 bug

### ISSUE THREAD

**Issue by itarcontact** [doctrine/persistence#81]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Doctrine\ORM\Configuration::setMetadataDriverImpl() must be an instance of Doctrine\Common\Persistence\Mapping\Driver\MappingDriver, instance of Doctrine\Persistence\Mapping\Driver\MappingDriverChain given

**Comment by mikaelcom** [comment]
> PHP Fatal error: Uncaught TypeError: Argument 1 passed to Doctrine\ORM\Configuration::setMetadataDriverImpl() must be an instance of Doctrine\Common\Persistence\Mapping\Driver\MappingDriver, instance of Doctrine\Persistence\Mapping\Driver\MappingDriverChain given

I just faced the issue too :cry:

**Comment by TomasVotruba** [comment]
Same here

**Comment by itarcontact** [comment]
I updated the symfony project today with a composer. Updated version of doctrine/persistence 1.3.1 with many deprecations. And now this bug with 1.3.2 version.

**Comment by TeQno** [comment]
same here

**Comment by michaljusiega** [comment]
https://github.com/doctrine/persistence/pull/80

The guys from doctrine are funny to me ...

**Comment by aguvillalba** [comment]
Same issue here in combination with laravel-doctrine package:

Argument 1 passed to Doctrine\ORM\Configuration::setMetadataDriverImpl() must be an instance of Doctrine\Common\Persistence\Mapping\Driver\MappingDriver, instance of Doctrine\ORM\Mapping\Driver\XmlDriver given, called in /code/vendor/laravel-doctrine/orm/src/EntityManagerFactory.php on line 167

**Comment by alexander-schranz** [comment]
You can add the broken version as a conflict to your `composer.json`:

```
{
    "conflict": {
        "doctrine/persistence": "1.3.2"
    }
}
```

Then 1.3.3 will install in future which I think will include definitly a fix for this issue.

**Comment by alcaeus** [comment]
1.3.3 has been released. I apologise for the problems. I’ll post a blog post about what we’re doing and why it failed later today or after the weekend. Thanks for understanding.

**Comment by Toflar** [comment]
And also folks: I don't know why this has come into fashion again but I see negative comments about broken releases happening all over the place in the PHP community lately (happened in Symfony too for example). It's not that people break things deliberately. Nobody releases versions with the intention to break other people's apps just for the fun of it. Being mad at people doesn't help anyone so let's make sure we support each other instead and keep up the good vibes.
So thank you Doctrine team for all your work and the quick fix! You're awesome! ❤️

**Comment by pacid** [comment]
I did compuser update yesterday and quickly the tests showed me I should not update. No biggie! That's awesome that it was so quickly fixed! One thing off my mind. Thanks Doctrine team! Love from :poland:

**Comment by MrMitch** [comment]
@alcaeus thank you for the new release. Where can we find the blog post you mention in your previous comment ?

**Comment by alcaeus** [comment]
It's currently being proofread and I hope to publish it soon. I'll post a link in this issue once it's done

**Comment by MrMitch** [comment]
@alcaeus wow, that was fast! thank you for the reply, looking forward to the post.

**Comment by alcaeus** [comment]
@MrMitch here we go: https://medium.com/@alcaeus/how-to-break-an-entire-ecosystem-by-publishing-a-release-b6aaab2b8aaa.

**Comment by MrMitch** [comment]
@alcaeus thank you, much appreciated.
