### ISSUE TITLE
Add support TypedNoDefaultReflectionProperty class to RuntimeReflectionService

### ISSUE THREAD

**Issue by sspat** [doctrine/persistence#89]
As suggested by @beberlei in doctrine/orm#7857
This is part of the implementation to fix this bug.

**Comment by sspat** [comment]
@greg0ire Could you please advise me on what version branch I should target with the implementation?

**Comment by greg0ire** [comment]
The lowest maintained branch is 1.2.x please target the lowest _affected_ branch (no idea which it is)

**Comment by beberlei** [comment]
Fixed
